' PlantUML ER Diagram
@startuml
@startchen

' Define entities
entity User {
    User ID <<key>>
    First Name
    Last Name
    Username
    Email
    Date of Birth
    Password
}

entity Item {
    Item ID <<key>>
    User ID <<FK>>
    Item Name
    Item In Date
    Quantity
}

entity Role {
    Role ID <<key>>
    Role Name
}

entity Household {
    Household ID <<key>>
    Household Name
}

entity Pantry {
    Pantry ID <<key>>
    Pantry Name
}

entity Recipe {
    Recipe ID <<key>>
    User ID <<FK>>
    Household ID <<FK>>
    Recipe Body
    Recipe Name
}

' Membership -> associative entity (between User and Household)
entity Member {
    Member ID <<key>>
    User ID <<FK>>
    Household ID <<FK>>
    Role ID <<FK>>
}

' Define relationships
relationship Holds {
}

relationship Contains {
}

relationship Owns {
}

relationship Adds {
}

relationship Authors {
}


' Create connections between relationships & entities
' --- User <-> Member <-> Household
User -N- Member
Member -M- Household

' --- Member -> Role
Member -1- Role

' --- Household <-> Pantry <-> Items
Household -1- Owns
Owns -M- Pantry
Pantry -1- Contains
Contains -M- Item

' --- User <-> Recipe (author/creator)
User -M- Authors
Authors -N- Recipe

' --- User <-> Items (ownership)
User -M- Adds
Adds -N- Item

' --- Household <-> Recipe (shared by household)
Household -M- Holds
Holds -N- Recipe

@endchen
@enduml
