@startuml
@startchen

entity User {
    User ID <<key>>
    Name
    Username
    Email
    Date of Birth
    Password
}
entity Household {
    Household ID <<key>>
    First Name
    Last Name
}
entity Pantry {
    Pantry ID <<key>>
    Pantry Name
}
entity Items {
    Item ID <<key>>
    Item Name
    Quantity
    Item In Date
}
relationship Member {
    Role
}
entity Recipe {
    Recipe ID <<key>>
    Recipe Body
    Recipe Name
}
relationship Holds {
}
relationship Contains {
}
relationship Owns {
}
relationship Adds {
}
relationship Authors {
}
User -N- Member
Member -M- Household
Household -1- Owns
Owns -M- Pantry
Pantry -1- Contains
Contains -M- Items 

User -M- Authors
Authors -N- Recipe
User -M- Adds
Adds -N- Items
Holds -N- Recipe
Household -M- Holds

@endchen
@enduml